on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test_download_and_install

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    steps:
      - uses: actions/checkout@v2

      - name: download
        run: |
          Rscript build-dep-list.R cpr qwraps2
        shell: bash


      - name: install
        run: |
          make
        shell: bash

